Add map popup link to selected feature
CxSci/SA-dashboard pull request #229
Opened 2022-03-28 08:19 UTC by torosyaneric

2022-03-28 22:19 UTC, justinanderson requested changes
- [ ] The location hash shouldn't be kept when sending a user to a detail page. For example, I clicked on a region and got sent to http://localhost:3000/explore/small-business/407031164#map=7.03/-34.462/137.697 but should have been sent to http://localhost:3000/explore/small-business/407031164.

- [ ] I'm seeing a focus outline around the popup's title just from mousing around the map. The title link shouldn't gain focus unless a user tabs to it. I think it's stealing focus whenever the popup becomes visible. I think `mapboxgl.Popup`'s `options.focusAfterOpen` default value is causing that to happen.
<img width="232" alt="Screen Shot 2022-03-28 at 6 07 57 PM" src="https://user-images.githubusercontent.com/244952/160496610-52703242-a092-4c67-8c96-7041797a4f14.png">

2022-03-29 16:42 UTC, justinanderson requested changes
- [ ] I just remembered that the chevron is supposed to be invisible when MapPopupContent isn't expanded. It should still take up space, just be invisible when not expanded, e.g. "Karoona Lameroo" should already wrap to two lines even when the popup isn't expanded.

2022-03-30 12:01 UTC, torosyaneric commented on frontend/src/components/Map/Map.js
> +      window.history.replaceState(null, null, ' ')
@justinanderson can't find a fix. Shall I implement custom hash updater along with setting map coords on init?

2022-03-30 12:02 UTC, torosyaneric commented
@justinanderson added popup chevron hiding.

2022-03-30 13:00 UTC, justinanderson commented on frontend/src/components/Map/Map.js
> +      window.history.replaceState(null, null, ' ')
Nah, maybe later. We don't have need yet on this page for links with hashes in them, so I'm inclined to leave this as a known issue for now. We can always make a custom hash updater later if that need changes.

2022-03-30 13:01 UTC, justinanderson approved these changes

2022-03-30 13:05 UTC, merged