Sa 252 comparison menu
CxSci/SA-dashboard pull request #260
Opened 2022-04-13 08:16 UTC by torosyaneric

Resolves #252

2022-04-14 22:24 UTC, justinanderson requested changes

2022-04-14 22:24 UTC, justinanderson commented on frontend/src/components/MapPopupContent/MapPopupContent.js
> +  }, [addToComparison, datasetId, dispatch, id, openCompareMenuOpen, title])
Adding a feature shouldn't wait until the geometry endpoint has responded successfully. The request might fail or take a long time to respond.

Also, all we should really store here is `id` and `title`. I wouldn't store `bbox` or `features`. We don't know how large the geometry response will be, and some uses of the Atlas might involve feature geometry which changes often enough that we won't want to cache stale versions.

2022-04-15 07:59 UTC, torosyaneric commented on frontend/src/components/ComparisonMenu/ComparisonMenu.js
> +              <StaticMap square areaId={item?.id} geoJSON={item} />
@justinanderson I think backend does not support fetching geoJson for multiple feature IDs yet:
` # TODO: Support requests for multiple ids`
`feature_id = feature_ids.split(" ")[0]`
 in `backend/api/views.py` `geometry_for_ids`
 
 Shall I make multiple queries for now?

2022-04-15 11:16 UTC, justinanderson commented on frontend/src/components/ComparisonMenu/ComparisonMenu.js
> +              <StaticMap square areaId={item?.id} geoJSON={item} />
Yes, please.

2022-04-20 17:33 UTC, torosyaneric commented
Fixed fetching issue. @justinanderson ready for review

2022-04-25 16:07 UTC, justinanderson requested changes
A lot better, but there's some odd behavior on Safari which was present in the previous commits as well. If the comparison menu opens because something was added to it (or if it's open and you mouse over one of the rows) then the menu jumps to the left and stays there. I'm still looking into what's going on with it, but if you have access to a machine with Safari you might have better luck diagnosing the issue.

Before mouseover:
<img width="1466" alt="Screen Shot 2022-04-25 at 12 02 51 PM" src="https://user-images.githubusercontent.com/244952/165128890-a967afb6-7c4e-41b1-a945-590cf6c31b73.png">

After mouseover:
<img width="1466" alt="Screen Shot 2022-04-25 at 12 02 41 PM" src="https://user-images.githubusercontent.com/244952/165128918-c00b3cdd-bda5-4453-b036-f5a9b398b8c9.png">

2022-04-29 20:33 UTC, merged