Truncate header breadcrumbs on smaller screens: rightmost items should be truncated first
CxSci/SA-dashboard pull request #283
Opened 2022-05-04 13:09 UTC by torosyaneric

Resolves #279

2022-05-05 16:17 UTC, justinanderson requested changes

2022-05-05 16:17 UTC, justinanderson commented on frontend/src/components/AtlasBreadcrumbs/AtlasBreadcrumbs.js
> +      const allocatedBreadcrumbsWidth = windowWidth - rightContentWidth - actionBtnWidth - 40
It would be good to include comments explaining where `16` and `40` come from, so we know if and how to change them in the future.

2022-05-05 20:06 UTC, torosyaneric commented on frontend/src/utils/theme.js
> +              '&.header__link--truncated': {
@justinanderson I've used [BEM](http://getbem.com/introduction/) naming. Do you want me to change to hyphens?

2022-05-05 20:14 UTC, justinanderson commented on frontend/src/utils/theme.js
> +              '&.header__link--truncated': {
@torosyaneric No, it's good as is. I just hadn't heard of BEM before. I didn't know `__` and `--` had specific meanings.

2022-05-06 15:59 UTC, leo-esaki commented on frontend/src/components/AtlasBreadcrumbs/AtlasBreadcrumbs.js
> +
Here's my suggestion:
We render 2 breadcrumbs one is for calculating the width of each item and its visibility will be hidden, along with aria-role set as none. that will remove the logic of manually cloning and adding DOMs to documents and setting css styles.
Also, using flexbox, the width of breadcrumb links area can be obtained just specifying a ref to the links container element. No need to calculate the width from left and right sections of the breadcrumbs.

2022-05-07 15:09 UTC, leo-esaki requested changes

2022-05-07 15:09 UTC, leo-esaki commented on frontend/src/components/AtlasBreadcrumbs/AtlasBreadcrumbs.js
> +          const ellipsisWidth = 22
Can you define a constant at the top of the component or in the .utils.js file?

2022-06-03 21:25 UTC, justinanderson approved these changes

2022-06-03 21:25 UTC, merged